-- 为 rsbt_plannning 表填充 ServiceType 和 BandType
-- 根据 radioservices 匹配 ServiceType，根据频率范围匹配 BandType
-- 注意：更具体的匹配放在前面，避免 "RADIO" 类错误匹配

-- Step 1: 更新 ServiceType (业务类型) - 顺序很重要，从最具体到最不具体

-- 1.1 卫星/空间 (最具体)
UPDATE rsbt_plannning SET SERVICETYPE = 'space' WHERE (RADIOSERVICES LIKE '%SPACE%' OR RADIOSERVICES LIKE '%SATELLITE%' OR RADIOSERVICES LIKE '%VSAT%') AND SERVICETYPE IS NULL;

-- 1.2 射电天文 (包含 RADIO ASTRONOMY)
UPDATE rsbt_plannning SET SERVICETYPE = 'radioastronomy' WHERE RADIOSERVICES LIKE '%RADIO ASTRONOMY%' AND SERVICETYPE IS NULL;

-- 1.3 无线电导航 (在 RADIO 之前匹配，避免被 %RADIO% 错误匹配)
UPDATE rsbt_plannning SET SERVICETYPE = 'radionavigation' WHERE (RADIOSERVICES LIKE '%RADIONAVIGATION%' OR RADIOSERVICES LIKE '%RADIONAV%') AND SERVICETYPE IS NULL;

-- 1.4 航空 (AERONAUTICAL)
UPDATE rsbt_plannning SET SERVICETYPE = 'aeronautical' WHERE (RADIOSERVICES LIKE '%AERONAUTICAL%' OR RADIOSERVICES LIKE '%AERONAV%') AND SERVICETYPE IS NULL;

-- 1.5 海上 (MARITIME)
UPDATE rsbt_plannning SET SERVICETYPE = 'maritime' WHERE (RADIOSERVICES LIKE '%MARITIME%' OR RADIOSERVICES LIKE '%MARITIM%') AND SERVICETYPE IS NULL;

-- 1.6 无线电定位 (RADIOLOCATION)
UPDATE rsbt_plannning SET SERVICETYPE = 'radiolocation' WHERE (RADIOSERVICES LIKE '%RADIOLOCATION%' OR RADIOSERVICES LIKE '%RADIOLOC%') AND SERVICETYPE IS NULL;

-- 1.7 业余 (AMATEUR)
UPDATE rsbt_plannning SET SERVICETYPE = 'amateur' WHERE (RADIOSERVICES LIKE '%AMATEUR%' OR RADIOSERVICES LIKE '%HAM%') AND SERVICETYPE IS NULL;

-- 1.8 标准频率和时间信号
UPDATE rsbt_plannning SET SERVICETYPE = 'standardfreq' WHERE RADIOSERVICES LIKE '%STANDARD FREQUENCY%' AND SERVICETYPE IS NULL;

-- 1.9 固定业务 (FIXED) - 但要排除包含其他关键词的
UPDATE rsbt_plannning SET SERVICETYPE = 'fixed' WHERE RADIOSERVICES LIKE '%FIXED%' AND SERVICETYPE IS NULL;

-- 1.10 移动业务 (MOBILE) - 但要排除航空和海上
UPDATE rsbt_plannning SET SERVICETYPE = 'mobile' WHERE (RADIOSERVICES LIKE '%MOBILE%' OR RADIOSERVICES LIKE '%CELLULAR%' OR RADIOSERVICES LIKE '%LTE%' OR RADIOSERVICES LIKE '%5G%') AND SERVICETYPE IS NULL;

-- 1.11 广播业务 (最后，避免被 %RADIO% 误匹配)
UPDATE rsbt_plannning SET SERVICETYPE = 'broadcasting' WHERE (RADIOSERVICES LIKE '%BROADCAST%' OR RADIOSERVICES LIKE '%TV%' OR RADIOSERVICES LIKE '%RADIO%' OR RADIOSERVICES LIKE '%TV%') AND SERVICETYPE IS NULL;

-- Step 2: 更新 BandType (频段类型) - 根据频率范围(kHz)

-- LW: 30 - 300 kHz
UPDATE rsbt_plannning SET BANGTYPE = 'LW'
WHERE BANGTYPE IS NULL AND STARTFREQUENCY IS NOT NULL
  AND (
    (STARTFREQUENCY LIKE '%kHz' AND CAST(REPLACE(REPLACE(STARTFREQUENCY, 'kHz', ''), ' ', '') AS DECIMAL(20,3)) >= 30 AND CAST(REPLACE(REPLACE(STARTFREQUENCY, 'kHz', ''), ' ', '') AS DECIMAL(20,3)) < 300)
    OR (STARTFREQUENCY NOT LIKE '%kHz' AND STARTFREQUENCY NOT LIKE '%MHz' AND STARTFREQUENCY NOT LIKE '%GHz' AND CAST(STARTFREQUENCY AS DECIMAL(20,3)) >= 30 AND CAST(STARTFREQUENCY AS DECIMAL(20,3)) < 300)
  );

-- MW: 300 kHz - 3 MHz (300 - 3000 kHz)
UPDATE rsbt_plannning SET BANGTYPE = 'MW'
WHERE BANGTYPE IS NULL AND STARTFREQUENCY IS NOT NULL
  AND (
    (STARTFREQUENCY LIKE '%kHz' AND CAST(REPLACE(REPLACE(STARTFREQUENCY, 'kHz', ''), ' ', '') AS DECIMAL(20,3)) >= 300 AND CAST(REPLACE(REPLACE(STARTFREQUENCY, 'kHz', ''), ' ', '') AS DECIMAL(20,3)) < 3000)
    OR (STARTFREQUENCY NOT LIKE '%kHz' AND STARTFREQUENCY NOT LIKE '%MHz' AND STARTFREQUENCY NOT LIKE '%GHz' AND CAST(STARTFREQUENCY AS DECIMAL(20,3)) >= 300 AND CAST(STARTFREQUENCY AS DECIMAL(20,3)) < 3000)
  );

-- SW: 3 MHz - 30 MHz (3000 - 30000 kHz)
UPDATE rsbt_plannning SET BANGTYPE = 'SW'
WHERE BANGTYPE IS NULL AND STARTFREQUENCY IS NOT NULL
  AND (
    (STARTFREQUENCY LIKE '%kHz' AND CAST(REPLACE(REPLACE(STARTFREQUENCY, 'kHz', ''), ' ', '') AS DECIMAL(20,3)) >= 3000 AND CAST(REPLACE(REPLACE(STARTFREQUENCY, 'kHz', ''), ' ', '') AS DECIMAL(20,3)) < 30000)
    OR (STARTFREQUENCY NOT LIKE '%kHz' AND STARTFREQUENCY NOT LIKE '%MHz' AND STARTFREQUENCY NOT LIKE '%GHz' AND CAST(STARTFREQUENCY AS DECIMAL(20,3)) >= 3000 AND CAST(STARTFREQUENCY AS DECIMAL(20,3)) < 30000)
  );

-- VHF: 30 MHz - 300 MHz (30000 - 300000 kHz)
UPDATE rsbt_plannning SET BANGTYPE = 'VHF'
WHERE BANGTYPE IS NULL AND STARTFREQUENCY IS NOT NULL
  AND (
    (STARTFREQUENCY LIKE '%MHz' AND CAST(REPLACE(REPLACE(STARTFREQUENCY, 'MHz', ''), ' ', '') AS DECIMAL(20,3)) >= 30 AND CAST(REPLACE(REPLACE(STARTFREQUENCY, 'MHz', ''), ' ', '') AS DECIMAL(20,3)) < 300)
    OR (STARTFREQUENCY LIKE '%kHz' AND CAST(REPLACE(REPLACE(STARTFREQUENCY, 'kHz', ''), ' ', '') AS DECIMAL(20,3)) >= 30000 AND CAST(REPLACE(REPLACE(STARTFREQUENCY, 'kHz', ''), ' ', '') AS DECIMAL(20,3)) < 300000)
    OR (STARTFREQUENCY NOT LIKE '%kHz' AND STARTFREQUENCY NOT LIKE '%MHz' AND STARTFREQUENCY NOT LIKE '%GHz' AND CAST(STARTFREQUENCY AS DECIMAL(20,3)) >= 30000 AND CAST(STARTFREQUENCY AS DECIMAL(20,3)) < 300000)
  );

-- UHF: 300 MHz - 3 GHz (300000 - 3000000 kHz)
UPDATE rsbt_plannning SET BANGTYPE = 'UHF'
WHERE BANGTYPE IS NULL AND STARTFREQUENCY IS NOT NULL
  AND (
    (STARTFREQUENCY LIKE '%MHz' AND CAST(REPLACE(REPLACE(STARTFREQUENCY, 'MHz', ''), ' ', '') AS DECIMAL(20,3)) >= 300 AND CAST(REPLACE(REPLACE(STARTFREQUENCY, 'MHz', ''), ' ', '') AS DECIMAL(20,3)) < 3000)
    OR (STARTFREQUENCY LIKE '%kHz' AND CAST(REPLACE(REPLACE(STARTFREQUENCY, 'kHz', ''), ' ', '') AS DECIMAL(20,3)) >= 300000 AND CAST(REPLACE(REPLACE(STARTFREQUENCY, 'kHz', ''), ' ', '') AS DECIMAL(20,3)) < 3000000)
    OR (STARTFREQUENCY NOT LIKE '%kHz' AND STARTFREQUENCY NOT LIKE '%MHz' AND STARTFREQUENCY NOT LIKE '%GHz' AND CAST(STARTFREQUENCY AS DECIMAL(20,3)) >= 300000 AND CAST(STARTFREQUENCY AS DECIMAL(20,3)) < 3000000)
  );

-- SHF: 3 GHz - 30 GHz (3000000 - 30000000 kHz)
UPDATE rsbt_plannning SET BANGTYPE = 'SHF'
WHERE BANGTYPE IS NULL AND STARTFREQUENCY IS NOT NULL
  AND (
    (STARTFREQUENCY LIKE '%GHz' AND CAST(REPLACE(REPLACE(STARTFREQUENCY, 'GHz', ''), ' ', '') AS DECIMAL(20,3)) >= 3 AND CAST(REPLACE(REPLACE(STARTFREQUENCY, 'GHz', ''), ' ', '') AS DECIMAL(20,3)) < 30)
    OR (STARTFREQUENCY LIKE '%MHz' AND CAST(REPLACE(REPLACE(STARTFREQUENCY, 'MHz', ''), ' ', '') AS DECIMAL(20,3)) >= 3000 AND CAST(REPLACE(REPLACE(STARTFREQUENCY, 'MHz', ''), ' ', '') AS DECIMAL(20,3)) < 30000)
    OR (STARTFREQUENCY LIKE '%kHz' AND CAST(REPLACE(REPLACE(STARTFREQUENCY, 'kHz', ''), ' ', '') AS DECIMAL(20,3)) >= 3000000 AND CAST(REPLACE(REPLACE(STARTFREQUENCY, 'kHz', ''), ' ', '') AS DECIMAL(20,3)) < 30000000)
  );

-- EHF: 30 GHz+
UPDATE rsbt_plannning SET BANGTYPE = 'EHF'
WHERE BANGTYPE IS NULL AND STARTFREQUENCY IS NOT NULL
  AND (
    (STARTFREQUENCY LIKE '%GHz' AND CAST(REPLACE(REPLACE(STARTFREQUENCY, 'GHz', ''), ' ', '') AS DECIMAL(20,3)) >= 30)
  );